name: NPE_LV
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::cpuonly
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - pandas
  - tqdm
  - pip
  - pip:
    - sbi
    - tensorboard